name: Python Lint and Format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install autopep8 flake8

    - name: Format code with autopep8
      run: autopep8 --in-place --aggressive --aggressive maya.py

    - name: Lint with flake8
      run: flake8 .
